name: wcap

on:
  push:
    paths-ignore:
      - '**/README.md'
  pull_request:
    paths-ignore:
      - '**/README.md'

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: repo

      - name: Build (x64)
        shell: cmd
        run: cd repo && build.cmd x64

      # - name: Build (arm64)
      #   shell: cmd
      #   run: cd repo && build.cmd arm64

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wcap
          path: repo\wcap-*.exe
